services:
    minio:
        image: minio/minio:latest
        container_name: minio_container
        ports:
            - "9000:9000" # S3 API
            - "9001:9001" # Web UI
        environment:
            MINIO_ROOT_USER: minio_admin
            MINIO_ROOT_PASSWORD: minio_password
        command: server /data --console-address ":9001"
        networks:
            - my-network
        volumes:
            - minio_data:/data
    
    postgres:    
        container_name: postgres_container
        image: postgres:16
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_password
            POSTGRES_DB: db
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
            - ./postgres/airflow-init.sql:/docker-entrypoint-initdb.d/airflow-init.sql
        healthcheck:
            test: ["CMD-SHELL","pg_isready -U db_user -d db"]
            interval: 5s
            retries: 5
        networks:
            - my-network

    af:
        container_name: airflow_container
        image: apache/airflow:3.0.0
        ports:
        - 8080:8080
        environment:
            AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow_db
            HF_API_KEY: "hfd_7c174cfb50eb466c9237d05700220412"
            MINIO_ENDPOINT: "http://minio:9000"
            MINIO_ACCESS_KEY: "minio_admin"
            MINIO_SECRET_KEY: "minio_password"
            HF_BASE_URL: "https://api.hfdatalibrary.com/v1"
            BUCKET: "lakehouse"
        group_add:
            - '1001'
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/config:/opt/airflow/config
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            postgres: 
                condition: service_healthy
        networks:
            - my-network
        command: >
            bash -c "airflow db migrate && 
            airflow standalone"
    
    nessie:
        image: projectnessie/nessie:latest
        container_name: nessie_container
        ports:
            - "19120:19120"
        environment:
            - QUARK_HTTP_PORT=19120
            - nessie.version.store.type=IN_MEMORY
        networks:
            - my-network
    
    spark:
        build: 
            context: ./spark
            dockerfile: Dockerfile
        container_name: spark_container
        ports:
            - "8081:8080"
            - "7077:7077"
        environment:
            - SPARK_MODE=master
            - AWS_ACCESS_KEY_ID=minio_admin
            - AWS_SECRET_ACCESS_KEY=minio_password
        command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
        volumes:
            - ./spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
        networks:
            - my-network
    
    spark-worker:
        build:
            context: ./spark
            dockerfile: Dockerfile
        environment:
            - SPARK_MODE=worker
            - AWS_ACCESS_KEY_ID=minio_admin
            - AWS_SECRET_ACCESS_KEY=minio_password
        command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077
        volumes:
            - ./spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
        depends_on:
            - spark
        networks:
            - my-network
    
    jupyter:
        image: jupyter/pyspark-notebook:latest
        container_name: jupyter_container
        ports:
            - "8888:8888"
        environment:
            JUPYTER_ENABLE_LAB: "yes"
        volumes:
            - ./notebooks:/home/jovyan/work
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
volumes:
    minio_data: